version: '3.7'

services:
  apache:
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    volumes:
    - ./public:/var/www/html/
    - .docker/php/xdebug.int:/usr/local/etc/php/php.ini
    ports:
    - 80:80
    networks:
      vrcube:
        aliases:
          - phpshop


networks:
  vrcube:
    external: true
